start: |
    Для начала работы с ботом воспользуйтесь одной из команд:

    🔸 /create - Создать новое мероприятие
    🔸 /find - Найти подходящее мероприятие
    🔸 /my_events - Мои мероприятия (посмотреть/изменить/удалить)

choose_date: Когда вы хотите провести ваше мероприятие?

choose_time: |
    Введите время старта, используя следующий формат.
    Указывайте время в 24-часовом формате, как указано ниже:
    15:00
    Если не знаете точное время старта или оно оговаривается, то укажите предполагаемый интервал времени в таком формате:
    07:00-09:00

choose_type: Что вы планируете провести?

choose_location: Где будет проходить ваше мероприятие?

choose_distance: Какое расстояние вы планируете преодолеть?

choose_pace: Какой темп (скорость) вы планируете поддерживать?

enter_additional_info: |
    Введите любую допольнительную информацию о пробежке.
    🔸 Это может быть: вид тренировки, описание интервалов, пожелания к участникам и т.д.
    🔸 Ограничение 200 символов.
    🔸 Если не хотите добавлять описание - просто отправьте дефис:
    -

event_created: Мероприятие успешно создано! 🎉

event_updated: Мероприятие успешно обновлено! 🎉

event_deleted: Мероприятие успешно удалено! 🎉

event_joined: Вы успешно присоединились к мероприятию! 🎉

event_unjoined: Вы успешно отписались от мероприятия! 🎉

event_published: Вы опубликовали мероприятие! 🎉

event_edited: Мероприятие успешно отредактировано! 🎉

unknown_command: Я не понимаю вас.

invalid_input: Некорректный ввод, попробуйте еще раз.

no_events: У вас пока нет мероприятий.

no_new_events: Нет новых мероприятий. Используйте /create чтобы создать своё.

choose_category: 🏃‍♂️ Выберите категорию мероприятий

i_m_author: Я создал

i_m_participant: Я участник

edit_message: Что вы хотите изменить?

event_info: |
    <b>{{title}}</b>

    🏃 Тип: {{event.type}}
    🕒 Время: {{event.formatted_time}}
    📍 Место: {{event.location}}
    {{#event.distance}}
    📏 Расстояние: {{event.distance}}
    {{/event.distance}}
    {{#event.pace}}
    🏃‍♂️ Темп/Скорость: {{event.pace}}
    {{/event.pace}}
    👤 Автор: {{#event.author.nickname}}@{{event.author.nickname}}{{/event.author.nickname}}{{^event.author.nickname}}{{event.author.username}}{{/event.author.nickname}}
    {{#event.additional_info}}
    📝 Описание: {{event.additional_info}}
    {{/event.additional_info}}
    {{#participants}}
    👥 Участники: {{participants}}
    {{/participants}}

edit_time: |
    Мероприятие запланировано на <b>{{event.time}}</b>.
    Введите новое время старта.

edit_location: |
    Вы планировали провести мероприятие здесь:
    <b>{{event.location}}</b>.
    Введите новое место проведения.

edit_info: |
    Введите новое описание.

time_saved: Время успешно сохранено!

location_saved: Место успешно сохранено!

info_saved: Описание успешно сохранено!

event_deleted_notification: |
    ❗️❗️ Внимание ❗️❗️ 
    Мероприятие <b>{{event.type}}</b>,
    запланированное на {{event.formatted_date}} {{event.time}}
    было удалено организатором.

time_changed_notification: |
    ❗️❗️ Внимание ❗️❗️ 
    Время мероприятия <b>{{event.type}}</b>,
    запланированное на {{event.formatted_date}}
    было изменено на:
    <b>{{new_time}}</b>.

location_changed_notification: |
    ❗️❗️ Внимание ❗️❗️ 
    Место проведения мероприятия <b>{{event.type}}</b>,
    запланированное на {{event.formatted_date}} {{event.time}}
    было изменено на:
    <b>{{new_location}}</b>.

info_changed_notification: |
    ❗️❗️ Внимание ❗️❗️ 
    Описание мероприятия <b>{{event.type}}</b>,
    запланированное на {{event.formatted_date}} {{event.time}}
    было изменено на:
    <b>{{new_info}}</b>

joined_notification: |
    У вас новый участник на мероприятии <b>{{event.type}}</b>,
    запланированном на {{event.formatted_date}} {{event.formatted_time}}.
    К вам присоединился:
    {{#user.nickname}}@{{user.nickname}}{{/user.nickname}}{{^user.nickname}}{{user.username}}{{/user.nickname}}.

no_events_today: На сегодня нет запланированных событий 🤷‍♂️.

no_events_today2: Сегодня нет совместных мероприятий 🤷‍♂️. Создай своё! Это легко 😉

no_events_tomorrow: На завтра нет запланированных событий 🤷‍♂️.

no_events_this_week: На ближайшую неделю нет запланированных событий 🤷‍♂️.

no_upcoming_events: На ближайшее время нет запланированных событий 🤷‍♂️.

events_for_today: |
    Мероприятия на сегодня:

# Добавим новые сообщения для публикации событий
publish_error: Произошла ошибка при публикации анонса.
publish_no_events: Нет мероприятий на сегодня. Отправлено сообщение в канал.
publish_success: Опубликовано {{count}} мероприятий в канале.

# Сообщения для веб-эндпоинта
web_no_events: No events scheduled for today.
web_publish_success: '{{count}} events published successfully.'
web_publish_error: An error occurred while publishing events.
