start: |
  Для начала работы с ботом воспользуйтесь одной из команд:

  🔸 /create - Создать новое мероприятие
  🔸 /find - Найти подходящее мероприятие
  🔸 /my_events - Мои мероприятия (посмотреть/изменить/удалить)

choose_date: Когда вы хотите провести ваше мероприятие?

choose_time: |
  Введите время старта, используя следующий формат.
  Указывайте время в 24-часовом формате, как указано ниже:
  15:00
  Если не знаете точное время старта или оно оговаривается, то укажите предполагаемый интервал времени в таком формате:
  07:00-09:00

choose_type: Что вы планируете провести?

choose_location: Где будет проходить ваше мероприятие?

choose_distance: Какое расстояние вы планируете преодолеть?

choose_pace: Какой темп (скорость) вы планируете поддерживать?

enter_additional_info: |
  Введите любую допольнительную информацию о пробежке.
  🔸 Это может быть: вид тренировки, описание интервалов, пожелания к участникам и т.д.
  🔸 Ограничение 200 символов.
  🔸 Если не хотите добавлять описание - просто отправьте дефис:
  -

event_created: Мероприятие успешно создано! 🎉

event_updated: Мероприятие успешно обновлено! 🎉

event_deleted: Мероприятие успешно удалено! 🎉

event_joined: Вы успешно присоединились к мероприятию! 🎉

event_unjoined: Вы успешно отписались от мероприятия! 🎉

unknown_command: Я не понимаю вас.

invalid_input: Некорректный ввод, попробуйте еще раз.

no_events: У вас пока нет мероприятий.

no_new_events: Нет новых мероприятий. Используйте /create чтобы создать своё.

choose_category: 🏃‍♂️ Выберите категорию мероприятий

i_m_author: Я создал

i_m_participant: Я участник

event_info: |
    <b>{{title}}</b>

    🏃 Тип: {{event.type}}
    🕒 Время: {{event.time}}
    📍 Место: {{event.location}}
    📏 Расстояние: {{event.distance}}
    🏃‍♂️ Темп: {{event.pace}}
    👤 Автор: @{{event.author.name}}
    📝 Описание: {{event.additional_info}}
    {{#participants}}
    👥 Участники: {{participants}}
    {{/participants}}
    ℹ️ Присоединившись, как участник, вы будете получать уведомления об изменениях в мероприятии. А организатору будет проще планировать детали.
