start: |
  Для начала работы с ботом воспользуйтесь одной из команд:

  🔸 /create - Создать новую пробежку
  🔸 /find - Найти подходящую пробежку
  🔸 /my_runs - Мои пробежки (посмотреть/изменить/удалить)
  🔸 /community_list - Список беговых чатов и сообществ Орла
  🔸 /feedback - Оставить отзыв или предложение

choose_date: Когда вы хотите провести ваше мероприятие?

choose_time: |
  Введите время старта, используя следующий формат.
  Указывайте время в 24-часовом формате, как указано ниже:
  15:00
  Если не знаете точное время старта или оно оговаривается, то укажите предполагаемый интервал времени в таком формате:
  07:00-09:00

choose_type: Что вы планируете провести?

choose_location: Где будет проходить ваше мероприятие?

choose_distance: Какое расстояние вы планируете преодолеть?

choose_pace: Какой темп (скорость) вы планируете поддерживать?

additional_info: |
  Введите любую допольнительную информацию о пробежке.
  🔸 Это может быть: вид тренировки, описание интервалов, пожелания к участникам и т.д.
  🔸 Ограничение 200 символов.
  🔸 Если не хотите добавлять описание - просто отправьте дефис:
  -
